[dev]
  command = "npm start"
  targetPort = 1234
  framework = "#custom"
  publish = "dist"
[build]
  functions = "functions"
[[redirects]]
  from = "/discogs/*"
  to = "/.netlify/functions/:splat"
  status = 200